[tool.poetry]
name = "bme-test"
version = "0.1.0"
description = ""
authors = ["Sudarshan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pandas = "^2.2.3"
numpy = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
